export enum ContractClientMessageType {
  createHero = 'create-hero',
  createHeroBehavior = 'create-hero-behavior',
  deleteHero = 'delete-hero',
  enterArea = 'enter-area',
  equipItem = 'equip-item',
  goToNextCombat = 'go-to-next-combat',
  leaveArea = 'leave-area',
  loadGame = 'load-game',
  sendChatMessage = 'send-chat-message',
  setCurrentHeroBehavior = 'set-current-hero-behavior',
  setSetting = 'set-setting',
  takeHeroSkillNode = 'take-hero-skill-node',
  updateHeroBehavior = 'update-hero-behavior',
}
