export enum ContractCharacterBehaviorTargetTypeKey {
  noTarget = 'no-target',
  specificHero = 'specific-hero',
  randomCharacter = 'random-character',
  randomAlly = 'random-ally',
  randomEnemy = 'random-enemy',
  randomCharacterMatchingPredicate = 'random-character-matching-predicate',
  randomAllyMatchingPredicate = 'random-ally-matching-predicate',
  randomEnemyMatchingPredicate = 'random-enemy-matching-predicate',
  characterWithTheLeastValue = 'character-with-the-least-value',
  allyWithTheLeastValue = 'ally-with-the-least-value',
  enemyWithTheLeastValue = 'enemy-with-the-least-value',
  characterWithTheMostValue = 'character-with-the-most-value',
  allyWithTheMostValue = 'ally-with-the-most-value',
  enemyWithTheMostValue = 'enemy-with-the-most-value',
}